# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  issues:
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  REVIEWER_ID: ${{(github.actor == 'Luryy' && '<@360205053031743491>') }} 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Test Success
        uses: rjstone/discord-webhook-notify@v1
        with:
            severity: info
            text: "New PR assign to ${{ env.REVIEWER_ID }} \n (PR LINK)[${{github.event.pull_request.url}}]"
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
            description: " - **Repository** ( ${{github.repository}} )[https://github.com/${{github.repository}}] \n -Author: ${{github.event.pull_request.user.login}}\n [Test](https://github.com/Luryy/Eco/blob/master/.github/workflows/main.yml) \n - **Assing**: ${{github.event.pull_request.requested_reviewers[0].user}}"
       
